"""Real-training SW evaluator (oracle mode).

Trains every individual on the remote cluster synchronously, returns
per-individual val_loss. Reuses RemoteTrainer + the YAML-payload format
shared with active learning.

Mirrors run_exp.py's flow but operates on a list of individuals (not a
Population). σ is reported as 0 — real training is the ground truth.
"""

from __future__ import annotations

import logging
import os
import time
from typing import Any, Dict, List, Tuple

from search_space import Individual

log = logging.getLogger("sw_real_train")
SCRIPT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def archs_to_training_yaml(archs: List[Dict[str, Any]], save_path: str) -> str:
    """Write a YAML matching the format `Population.to_yaml` emits.
    Each arch gets a sequential idx (1..N) so the trainer's CSV lookup works.
    """
    os.makedirs(os.path.dirname(save_path) or ".", exist_ok=True)
    lines = ["# Real-training payload",
             "# Generated by evaluators/sw_real_train.py", ""]
    n_kept = 0
    for i, ind in enumerate(archs):
        g = ind["globals"] if "globals" in ind else ind
        layers = ind.get("layers", [])
        mask = g.get("layer_mask", [True] * len(layers))
        active = [j for j, m in enumerate(mask) if m]
        if not active:
            continue
        n_kept += 1
        lines.append(f"- idx: {i + 1}")
        for k, v in g.items():
            if k != "layer_mask":
                lines.append(f"  {k}: {v}")
        if layers:
            for key in layers[0].keys():
                if key.endswith("_exp"):
                    arg = f"{key[:-4]}_layerlist"
                    ll = [2 ** layers[j].get(key) for j in active]
                else:
                    arg = f"{key}_layerlist"
                    ll = [layers[j].get(key) for j in active]
                lines.append(f"  {arg}: {ll}")
        lines.append(f"# n_layers: {len(active)}")
        lines.append("")
    with open(save_path, "w") as f:
        f.write("\n".join(lines))
    return save_path


class SwRealTrain:
    """Synchronous real-training evaluator. NSGA blocks until all jobs finish."""

    def __init__(self, *, hosts_file: str, user: str, ssh_key: str,
                 conda_env: str, remote_llmforge_train_dir: str,
                 max_iters: int, timeout: int,
                 exp_name: str, dataset: str = "minipile",
                 payload_dir: str = "train",
                 poll_interval: int = 120):
        from run_exp import load_hosts_from_file
        hp = hosts_file if os.path.isabs(hosts_file) else os.path.join(SCRIPT_DIR, hosts_file)
        self.hosts = load_hosts_from_file(hp)
        self.user = user
        self.ssh_key = ssh_key
        self.conda_env = conda_env
        self.remote_llmforge_train_dir = remote_llmforge_train_dir
        self.max_iters = int(max_iters)
        self.timeout = int(timeout)
        self.poll_interval = int(poll_interval)
        self.exp_name = exp_name
        self.dataset = dataset
        self.payload_dir = payload_dir
        self._gen = 0
        log.info(f"[real-train] {len(self.hosts)} hosts loaded from {hp}")
        # Pre-pull on remote hosts so the first eval doesn't wait
        from remote_trainer import RemoteTrainer
        self._RemoteTrainer = RemoteTrainer
        trainer = RemoteTrainer(hosts=self.hosts, user=user, key_filename=ssh_key)
        trainer.perform_git_pull(remote_work_dir=remote_llmforge_train_dir)

    def set_gen(self, gen: int) -> None:
        """Tag subsequent payloads with the current generation index."""
        self._gen = int(gen)

    def evaluate(self, inds: List[Individual]) -> Tuple[List[float], List[float]]:
        if not inds:
            return [], []
        gen = self._gen
        payload = os.path.join(self.payload_dir, self.exp_name, f"gen{gen}.yaml")
        archs_to_training_yaml(inds, payload)

        trainer = self._RemoteTrainer(hosts=self.hosts, user=self.user,
                                      key_filename=self.ssh_key)
        dir_name = f"{self.exp_name}/gen{gen}"
        log.info(f"[real-train] submit gen{gen}: {len(inds)} archs, "
                 f"max_iters={self.max_iters}, timeout={self.timeout}s")
        ok = trainer.submit_job(
            path_to_yaml=payload, remote_work_dir=self.remote_llmforge_train_dir,
            dir_name=dir_name, conda_env=self.conda_env,
            max_iters=self.max_iters, dataset=self.dataset,
        )
        if not ok:
            log.warning("[real-train] submit_job returned non-OK; returning NaN labels")
            nan = float("nan")
            return [nan] * len(inds), [0.0] * len(inds)

        time.sleep(5)
        trainer.poll_jobs()
        trainer.wait_for_all(poll_interval=self.poll_interval,
                             timeout=self.timeout, verbose=True)

        local_dir = os.path.join("train", self.exp_name)
        os.makedirs(local_dir, exist_ok=True)
        csv_path = trainer.fetch_results(gen=gen, local_dir=local_dir)
        from nsga2 import load_csv_with_idx_lookup
        try:
            data = load_csv_with_idx_lookup(csv_path)
        except Exception as e:
            log.warning(f"[real-train] failed to parse {csv_path}: {e}")
            data = {}
        # Missing rows + NaN entries collapse to inf so NSGA non-domination
        # has a well-defined ordering. Downstream consumers (e.g. SwFinetune)
        # filter inf/NaN before refitting, but the dispatcher path needs a
        # finite or +inf number.
        def _coerce(v):
            try:
                fv = float(v)
            except (TypeError, ValueError):
                return float("inf")
            return float("inf") if fv != fv else fv
        labels = [_coerce(data.get(i + 1, float("inf"))) for i in range(len(inds))]
        n_ok = sum(1 for v in labels if v != float("inf"))
        log.info(f"[real-train] gen{gen}: fetched {n_ok}/{len(inds)} val_loss "
                 f"labels (csv={csv_path})")
        return labels, [0.0] * len(labels)
